Repository k-shimari/nod3v, pull requests merged in 2019-10, with the labels that each got.

#98 Fix #97
  frontend/src/app/components/atoms/valueListItem.tsx
  frontend/src/app/components/organisms/valueList.tsx
  frontend/src/app/models/api.ts
Labels: frontend

#103 bug fix getjson in sorting dataids by linenums
  src/createjson/CreateVarInfo.java
  src/data/methodparam/MethodParam.java
Labels: backend

#108 Fix increment
  src/createjson/CreateVarInfo.java
Labels: backend, bug
